# Generated by Django 4.1.2 on 2022-11-18 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998 [XX] [XXX XX XX]'. Up to 13 digits allowed.", regex='^+998[0-9]{9}$')]),
        ),
    ]
